// The icons.css file is generated by build-icons.ts
// For development, we'll use a basic CSS file we've created manually
import './icons.css';

export default function () {
  // This plugin just requires icons import
}
